name: Sync model.json to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync Files
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }} 
          SKIP_PR: true


